import { AppTheme } from "./../theme/theme";
export type ChallengeType = {
  name: string;
  type: string;
  color: keyof AppTheme["colors"];
  containerColor: keyof AppTheme["colors"];
  progressColor: keyof AppTheme["colors"];
  progress?: number;
  currentProgress?: number;
  day?: number;
  month?: number;
  year?: number;
  goal?: number;
  icon: string;
  score: number;
  grade: number;
  id: number;
};

export const allChallenges: ChallengeType[] = [
  {
    name: "Generate 1 Route",
    type: "route_generation",
    color: "onPrimaryContainer",
    containerColor: "primaryContainer",
    icon: "routes",
    progressColor: "primary",
    score: 1,
    grade: 1,
    id: 1,
  },
  {
    name: "Generate 5 Routes",
    type: "route_generation",
    color: "onPrimaryContainer",
    containerColor: "primaryContainer",
    progressColor: "primary",
    icon: "routes",
    score: 3,
    grade: 2,
    id: 2,
  },
  {
    name: "Generate 10 Routes",
    type: "route_generation",
    color: "onPrimaryContainer",
    containerColor: "primaryContainer",
    progressColor: "primary",
    icon: "routes",
    score: 5,
    grade: 3,
    id: 3,
  },
  {
    name: "Favorite 1 Route",
    type: "favourited",
    color: "onAmberContainer",
    containerColor: "amberContainer",
    progressColor: "amber",
    icon: "bookmark-check-outline",
    score: 1,
    grade: 1,
    id: 4,
  },
  {
    name: "Favorite 5 Routes",
    type: "favourited",
    color: "onAmberContainer",
    containerColor: "amberContainer",
    progressColor: "amber",
    icon: "bookmark-check-outline",
    score: 3,
    grade: 2,
    id: 5,
  },
  {
    name: "Favorite 10 Routes",
    type: "favourited",
    color: "onAmberContainer",
    containerColor: "amberContainer",
    progressColor: "amber",
    icon: "bookmark-check-outline",
    score: 5,
    grade: 3,
    id: 6,
  },
  {
    name: "Share 1 Route",
    type: "shared",
    color: "onSuccessContainer",
    containerColor: "successContainer",
    progressColor: "success",
    icon: "share",
    score: 1,
    grade: 1,
    id: 7,
  },
  {
    name: "Share 5 Routes",
    type: "shared",
    color: "onSuccessContainer",
    containerColor: "successContainer",
    progressColor: "success",
    icon: "share",
    score: 3,
    grade: 2,
    id: 8,
  },
  {
    name: "Share 10 Routes",
    type: "shared",
    color: "onSuccessContainer",
    containerColor: "successContainer",
    progressColor: "success",
    icon: "share",
    score: 5,
    grade: 3,
    id: 9,
  },
  {
    name: "Publish 1 Route",
    type: "published",
    color: "onPinkContainer",
    containerColor: "pinkContainer",
    progressColor: "pink",
    icon: "monitor-share",
    score: 1,
    grade: 1,
    id: 10,
  },
  {
    name: "Publish 5 Routes",
    type: "published",
    color: "onPinkContainer",
    containerColor: "pinkContainer",
    progressColor: "pink",
    icon: "monitor-share",
    score: 3,
    grade: 2,
    id: 11,
  },
  {
    name: "Publish 10 Route",
    type: "published",
    color: "onPinkContainer",
    containerColor: "pinkContainer",
    progressColor: "pink",
    icon: "monitor-share",
    score: 5,
    grade: 3,
    id: 12,
  },
  {
    name: "Read 1 Tip",
    type: "read_tips",
    color: "onTealContainer",
    containerColor: "tealContainer",
    progressColor: "teal",
    icon: "book-check",
    score: 1,
    grade: 1,
    id: 13,
  },
  {
    name: "Read 5 Tips",
    type: "read_tips",
    color: "onTealContainer",
    containerColor: "tealContainer",
    progressColor: "teal",
    icon: "book-check",
    score: 3,
    grade: 2,
    id: 14,
  },
  {
    name: "Read 10 Tips",
    type: "read_tipes",
    color: "onTealContainer",
    containerColor: "tealContainer",
    progressColor: "teal",
    icon: "book-check",
    score: 5,
    grade: 3,
    id: 15,
  },
  {
    name: "Daily Log In",
    type: "logged_in",
    color: "onPurpleContainer",
    containerColor: "purpleContainer",
    progressColor: "purple",
    icon: "login",
    score: 1,
    grade: 1,
    id: 16,
  },
  {
    name: "Access Global Feed",
    type: "accessed_global_feed",
    color: "onBrownContainer",
    containerColor: "brownContainer",
    progressColor: "brown",
    icon: "broadcast",
    score: 1,
    grade: 1,
    id: 17,
  },
];
