export const getRouteImage = (photo: string) => {
  switch (photo) {
    case "landmarks/Arcade":
      return require("../assets/images/feedcards/landmark/Arcade.jpg");
    case "landmark/Arcade2":
      return require("../assets/images/feedcards/landmark/Arcade2.jpg");
    case "landmark/Arcade3":
      return require("../assets/images/feedcards/landmark/Arcade3.jpg");
    case "landmark/Brighton":
      return require("../assets/images/feedcards/landmark/Brighton.jpg");
    case "landmark/CBD1":
      return require("../assets/images/feedcards/landmark/CBD1.jpg");
    case "landmark/CBD2":
      return require("../assets/images/feedcards/landmark/CBD2.jpg");
    case "landmark/CBD3":
      return require("../assets/images/feedcards/landmark/CBD3.jpg");
    case "landmark/CBD4":
      return require("../assets/images/feedcards/landmark/CBD4.jpg");
    case "landmark/CBD5":
      return require("../assets/images/feedcards/landmark/CBD5.jpg");
    case "landmark/Chinatown":
      return require("../assets/images/feedcards/landmark/Chinatown.jpg");
    case "landmark/Flinder_Station":
      return require("../assets/images/feedcards/landmark/Flinder_Station.jpg");
    case "landmark/Flinder_Station_2":
      return require("../assets/images/feedcards/landmark/Flinder_Station_2.jpg");
    case "landmark/Hare_Krishna_Temple":
      return require("../assets/images/feedcards/landmark/Hare_Krishna_Temple.jpg");
    case "landmark/Park":
      return require("../assets/images/feedcards/landmark/Park.jpg");
    case "landmark/Park2":
      return require("../assets/images/feedcards/landmark/Park2.jpg");
    case "landmark/Pier":
      return require("../assets/images/feedcards/landmark/Pier.jpg");
    case "landmark/Stairs":
      return require("../assets/images/feedcards/landmark/Stairs.jpg");
    case "landmark/Train":
      return require("../assets/images/feedcards/landmark/Train.jpg");
    case "grocery/Grocery":
      return require("../assets/images/feedcards/grocery/Grocery.jpg");
    case "grocery/Market":
      return require("../assets/images/feedcards/grocery/Market.jpg");
    case "pharmacy/Blood_Pressure":
      return require("../assets/images/feedcards/pharmacy/Blood_Pressure.jpg");
    case "pharmacy/Dental":
      return require("../assets/images/feedcards/pharmacy/Dental.jpg");
    case "pharmacy/Fish_Oil":
      return require("../assets/images/feedcards/pharmacy/Fish_Oil.jpg");
    case "pharmacy/Pain":
      return require("../assets/images/feedcards/pharmacy/Pain.jpg");
    case "pharmacy/Pharmacist":
      return require("../assets/images/feedcards/pharmacy/Pharmacist.jpg");
    case "restaurant/Breakie":
      return require("../assets/images/feedcards/restaurant/Breakie.jpg");
    case "restaurant/Burger":
      return require("../assets/images/feedcards/restaurant/Burger.jpg");
    case "restaurant/Chinese Skew":
      return require("../assets/images/feedcards/restaurant/Chinese_Skew.jpg");
    case "restaurant/Chinese_Fancy":
      return require("../assets/images/feedcards/restaurant/Chinese_Fancy.jpg");
    case "restaurant/Chinese_Noodles":
      return require("../assets/images/feedcards/restaurant/Chinese_Noodles.jpg");
    case "restaurant/Coffee":
      return require("../assets/images/feedcards/restaurant/Coffee.jpg");
    case "restaurant/Fruit_Bowl":
      return require("../assets/images/feedcards/restaurant/Fruit_Bowl.jpg");
    case "restaurant/Indian_Fried_Food":
      return require("../assets/images/feedcards/restaurant/Indian_Fried_Food.jpg");
    case "restaurant/Indian_Preserved":
      return require("../assets/images/feedcards/restaurant/Indian_Preserved.jpg");
    case "restaurant/Indian_Rojak":
      return require("../assets/images/feedcards/restaurant/Indian_Rojak.jpg");
    case "restaurant/Indian_Roti":
      return require("../assets/images/feedcards/restaurant/Indian_Roti.jpg");
  }
};
