
name: Build and Push Images - GHCR

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build_push_images:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            tag: ghcr.io/topmello/settle-aid-frontend:latest


    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: 'actions/checkout@v3'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build and push Docker image to Dockerhub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ matrix.tag }}
        context: .
        file: ${{ matrix.dockerfile }}

    
    

